//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analize_Factura
    {
        public int id_serviciu { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> id_analize { get; set; }
        public string activ { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Buletin_Analize Buletin_Analize { get; set; }
    }
}
