//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asigurare
    {
        public int id_asigurare { get; set; }
        public Nullable<int> id_asigurator { get; set; }
        public Nullable<int> id_pacient { get; set; }
        public Nullable<System.DateTime> data_asigurare { get; set; }
        public Nullable<System.DateTime> data_expirare { get; set; }
    
        public virtual Asigurari Asigurari { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
