//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buletin_Analize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buletin_Analize()
        {
            this.Analize_Factura = new HashSet<Analize_Factura>();
            this.Rezultat_Analize = new HashSet<Rezultat_Analize>();
        }
    
        public int id_buletin { get; set; }
        public Nullable<int> id_formular_analize { get; set; }
        public Nullable<int> id_pacient { get; set; }
        public Nullable<System.DateTime> data_recoltare { get; set; }
        public Nullable<int> id_seflab { get; set; }
        public string activ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analize_Factura> Analize_Factura { get; set; }
        public virtual Angajat Angajat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezultat_Analize> Rezultat_Analize { get; set; }
        public virtual Formular_Analize Formular_Analize { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
