//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clinica()
        {
            this.Departaments = new HashSet<Departament>();
            this.Facturas = new HashSet<Factura>();
            this.Functies = new HashSet<Functie>();
        }
    
        public int id_clinica { get; set; }
        public string nume_clinica { get; set; }
        public string judet { get; set; }
        public string oras { get; set; }
        public string adresa { get; set; }
        public string program { get; set; }
        public string nr_contact { get; set; }
        public string email { get; set; }
        public string CIF { get; set; }
        public string IBAN { get; set; }
        public string Banca { get; set; }
        public string cale_imagine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departament> Departaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Functie> Functies { get; set; }
    }
}
