//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultatie()
        {
            this.Diagnostics = new HashSet<Diagnostic>();
            this.Consultatii_Factura = new HashSet<Consultatii_Factura>();
        }
    
        public int id_consultatie { get; set; }
        public Nullable<int> id_doctor { get; set; }
        public Nullable<int> id_asistent { get; set; }
        public Nullable<int> id_pacient { get; set; }
        public Nullable<System.DateTime> data_consultatie { get; set; }
        public string ora { get; set; }
        public Nullable<decimal> pret { get; set; }
        public string activ { get; set; }
    
        public virtual Angajat Angajat { get; set; }
        public virtual Angajat Angajat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostic> Diagnostics { get; set; }
        public virtual Pacient Pacient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultatii_Factura> Consultatii_Factura { get; set; }
    }
}
