//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostic
    {
        public int id_diagnostic { get; set; }
        public Nullable<int> id_consultatie { get; set; }
        public string diagnostic1 { get; set; }
        public string observatii { get; set; }
        public string tratament { get; set; }
        public string activ { get; set; }
    
        public virtual Consultatie Consultatie { get; set; }
    }
}
