//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Analize_Factura = new HashSet<Analize_Factura>();
            this.Consultatii_Factura = new HashSet<Consultatii_Factura>();
        }
    
        public int id_factura { get; set; }
        public Nullable<int> id_pacient { get; set; }
        public Nullable<int> id_clinica { get; set; }
        public string modalitate_plata { get; set; }
        public string activ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analize_Factura> Analize_Factura { get; set; }
        public virtual Clinica Clinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultatii_Factura> Consultatii_Factura { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
