//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incadrare_Departament
    {
        public int id_incadrare { get; set; }
        public Nullable<int> id_departament { get; set; }
        public Nullable<int> id_angajat { get; set; }
        public string intrare_tura { get; set; }
        public string iesire_tura { get; set; }
        public string activ { get; set; }
    
        public virtual Angajat Angajat { get; set; }
        public virtual Departament Departament { get; set; }
    }
}
