//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezultat_Analize
    {
        public int id_rezultat { get; set; }
        public Nullable<int> id_buletin_analize { get; set; }
        public Nullable<int> id_analiza { get; set; }
        public string valori_rezultate { get; set; }
    
        public virtual Analize Analize { get; set; }
        public virtual Buletin_Analize Buletin_Analize { get; set; }
    }
}
